# Generated by Django 3.2.5 on 2022-04-22 22:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='timeNotes',
            new_name='timeNote',
        ),
    ]
